apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: game-demo
  labels:
    app: nginx
    app.kubernetes.io/instance: some-application
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: dukex/dummy-nginx:0daef29f251bae105d283706d51dd585853d9c96
        name: nginx
        ports:
        - containerPort: 80
