---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  type: ClusterIP
  ports:
    - name: nginx-deployment
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-deployment
