apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dukex/argocd-test-app.git'
    path: ./k8s
    targetRevision: development
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dukex/argocd-test-app.git'
    path: ./k8s
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
  orphanedResources:
    warn: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-prd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dukex/argocd-test-app.git'
    path: ./k8s
    targetRevision: v1.0.0
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  orphanedResources:
    warn: true
  syncPolicy:
    syncOptions:
    - PruneLast=true