name: Build & Test
on:
  push:
    branches:
      - development
      - main

jobs:
  build-and-test:
    name: "Build & Test"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dukex
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t dukex/dummy-nginx:${{ github.sha }} .
      - name: Push
        run: docker push dukex/dummy-nginx:${{github.sha}}